server {
    listen 80;
server_name _;
    # chạy port 80 , _= chấp nhận mọi domain

    root /usr/share/nginx/html;
    index index.html;
# thưu mục chưa frontend
# file mặc định là index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
# nếu nginx không tìm thấy file -> thay vì 4040 thì sẽ fallback về index.html
    location /api/ {
        proxy_pass http://backend:8080/api/;
        #mọi request /api/.. sẽ trỏ về backend container
        proxy_set_header Host $host;
        # Giữ domain gốc
        proxy_set_header X-Real_IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Lưu ip client thật
        proxy_set_header X-Forwarded_Proto $scheme;
    }
}