export const SUBJECTS = ["HSK 1", "HSK 2", "HSK 3", "HSK 4", "HSK 5", "HSK 6"];
export const EXAM_SUBJECTS = ["HSK 1", "HSK 2", "HSK 3", "HSK 4", "HSK 5", "HSK 6"];

const samplePdfUrl = "/documents/sample-toxi.pdf";

export const DOC_DATA = [
  {
    id: 1,
    type: "document",
    level: "HSK 1",
    brand: "Tài liệu tổng hợp HSK 1",
    titleInner: "Từ vựng cơ bản và pinyin",
    subtitle: "Tài liệu ôn tập nhập môn dành cho người mới bắt đầu",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "HSK 1 tổng hợp từ vựng cơ bản, pinyin và mẫu câu giao tiếp hằng ngày",
    date: "05/04/2026",
    views: 2671,
    downloads: 913,
    thumbColor: ["#e8f4fd", "#c3ddf5"],
    description:
      "Bộ tài liệu tổng hợp dành cho người mới học HSK 1, gồm pinyin, từ vựng nền tảng, mẫu câu giao tiếp và bài luyện ngắn.",
    pdfUrl: samplePdfUrl,
    fileName: "hsk-1-tu-vung-pinyin.pdf",
  },
  {
    id: 2,
    type: "document",
    level: "HSK 2",
    brand: "Tài liệu tổng hợp HSK 2",
    titleInner: "Hệ thống mẫu câu thông dụng",
    subtitle: "Mẫu câu tần suất cao và bài luyện hội thoại cơ bản",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "HSK 2 tổng hợp mẫu câu thông dụng, cấu trúc hỏi đáp và từ vựng theo chủ đề",
    date: "05/04/2026",
    views: 1840,
    downloads: 721,
    thumbColor: ["#e8f4fd", "#c3ddf5"],
    description: "Tài liệu bám sát các tình huống hội thoại thường gặp, phù hợp để luyện phản xạ ở trình độ HSK 2.",
    pdfUrl: samplePdfUrl,
    fileName: "hsk-2-mau-cau-thong-dung.pdf",
  },
  {
    id: 3,
    type: "document",
    level: "HSK 3",
    brand: "Tài liệu tổng hợp HSK 3",
    titleInner: "Tổng hợp ngữ pháp trọng điểm",
    subtitle: "Hệ thống các điểm ngữ pháp thường gặp trong bài thi",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "HSK 3 tổng hợp ngữ pháp tần suất cao, từ nối và kỹ năng đọc hiểu",
    date: "25/03/2026",
    views: 2695,
    downloads: 1184,
    thumbColor: ["#e8f4fd", "#c3ddf5"],
    description: "Tập trung vào các cấu trúc ngữ pháp cốt lõi và bài đọc ngắn giúp củng cố nền tảng HSK 3.",
    pdfUrl: samplePdfUrl,
    fileName: "hsk-3-ngu-phap-trong-diem.pdf",
  },
  {
    id: 4,
    type: "document",
    level: "HSK 4",
    brand: "Tài liệu tổng hợp HSK 4",
    titleInner: "Chuyên đề đọc hiểu",
    subtitle: "Nâng cao tốc độ đọc và độ chính xác khi làm bài",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "HSK 4 tuyển tập bài đọc hiểu, cụm từ đi kèm và bài luyện chọn lọc",
    date: "02/02/2026",
    views: 5086,
    downloads: 2095,
    thumbColor: ["#e8f4fd", "#c3ddf5"],
    description: "Bộ đề đọc hiểu được biên soạn theo mức độ tăng dần, hỗ trợ tăng tốc độ xử lý bài thi HSK 4.",
    pdfUrl: samplePdfUrl,
    fileName: "hsk-4-doc-hieu.pdf",
  },
  {
    id: 5,
    type: "document",
    level: "HSK 5",
    brand: "Tài liệu tổng hợp HSK 5",
    titleInner: "Chuyên sâu từ vựng nâng cao",
    subtitle: "Phân biệt từ khó và tích lũy cách diễn đạt trong đề thật",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "HSK 5 chuyên đề từ vựng nâng cao, diễn đạt viết và đọc hiểu chuyên sâu",
    date: "01/02/2026",
    views: 3243,
    downloads: 1473,
    thumbColor: ["#e8f4fd", "#c3ddf5"],
    description: "Tổng hợp nhóm từ nâng cao, collocation và cấu trúc biểu đạt thường xuất hiện ở HSK 5.",
    pdfUrl: samplePdfUrl,
    fileName: "hsk-5-tu-vung-nang-cao.pdf",
  },
  {
    id: 6,
    type: "document",
    level: "HSK 6",
    brand: "Tài liệu tổng hợp HSK 6",
    titleInner: "Tổng hợp điểm khó đề thật",
    subtitle: "Phá vỡ các phần khó trong đọc hiểu và nghe hiểu nâng cao",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "HSK 6 tổng hợp điểm khó thường gặp, từ gần nghĩa và kỹ năng viết nâng cao",
    date: "15/01/2026",
    views: 3891,
    downloads: 1682,
    thumbColor: ["#fff8e1", "#ffe082"],
    description: "Bộ tài liệu chuyên sâu cho HSK 6, tập trung vào phần từ gần nghĩa, đọc dài và viết học thuật.",
    pdfUrl: samplePdfUrl,
    fileName: "hsk-6-diem-kho-de-that.pdf",
  },
];

export const EXAM_DATA = [
  {
    id: 1,
    type: "exam",
    level: "HSK 1",
    brand: "Đề thi thử HSK 1",
    titleInner: "Đề mô phỏng HSK 1",
    subtitle: "Từ vựng - Nghe - Đọc",
    note: "Thời gian gợi ý: 40 phút",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "Đề thi thử HSK 1 số 1: luyện từ vựng cơ bản và nghe hiểu nhập môn",
    date: "03/04/2026",
    views: 4120,
    downloads: 1752,
    description: "Đề mô phỏng chuẩn cấu trúc HSK 1, thích hợp để luyện tốc độ làm bài và làm quen dạng câu hỏi.",
    pdfUrl: samplePdfUrl,
    fileName: "de-thi-thu-hsk-1-so-1.pdf",
  },
  {
    id: 2,
    type: "exam",
    level: "HSK 2",
    brand: "Đề thi thử HSK 2",
    titleInner: "Đề mô phỏng HSK 2",
    subtitle: "Mẫu câu - Ngữ pháp - Nghe",
    note: "Thời gian gợi ý: 55 phút",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "Đề thi thử HSK 2 số 2: luyện mẫu câu thường gặp và nghe hiểu cơ bản",
    date: "02/04/2026",
    views: 3870,
    downloads: 1491,
    description: "Phù hợp cho người học đang cần kiểm tra lại phản xạ ngữ pháp và kỹ năng nghe ở HSK 2.",
    pdfUrl: samplePdfUrl,
    fileName: "de-thi-thu-hsk-2-so-2.pdf",
  },
  {
    id: 3,
    type: "exam",
    level: "HSK 3",
    brand: "Đề thi thử HSK 3",
    titleInner: "Đề mô phỏng HSK 3",
    subtitle: "Ngữ pháp - Đọc - Viết cơ bản",
    note: "Thời gian gợi ý: 90 phút",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "Đề thi thử HSK 3 số 3: kiểm tra tổng hợp ngữ pháp, đọc và viết cơ bản",
    date: "28/03/2026",
    views: 5201,
    downloads: 2236,
    description: "Đề tổng hợp đủ ba kỹ năng với độ khó sát thực tế, có thể dùng để tự kiểm tra trước kỳ thi.",
    pdfUrl: samplePdfUrl,
    fileName: "de-thi-thu-hsk-3-so-3.pdf",
  },
  {
    id: 4,
    type: "exam",
    level: "HSK 4",
    brand: "Đề thi thử HSK 4",
    titleInner: "Đề mô phỏng HSK 4",
    subtitle: "Đọc - Nghe - Diễn đạt viết",
    note: "Thời gian gợi ý: 105 phút",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "Đề thi thử HSK 4 số 4: luyện tốc độ đọc và kỹ năng diễn đạt viết",
    date: "20/03/2026",
    views: 2984,
    downloads: 1212,
    description: "Bộ đề giúp luyện kỹ năng phân bổ thời gian và nâng độ chính xác ở các phần đọc và viết.",
    pdfUrl: samplePdfUrl,
    fileName: "de-thi-thu-hsk-4-so-4.pdf",
  },
  {
    id: 5,
    type: "exam",
    level: "HSK 5",
    brand: "Đề thi thử HSK 5",
    titleInner: "Đề mô phỏng HSK 5",
    subtitle: "Từ vựng nâng cao - Đọc - Nghe",
    note: "Thời gian gợi ý: 125 phút",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "Đề thi thử HSK 5 số 5: luyện tổng hợp đọc hiểu, nghe hiểu và từ vựng nâng cao",
    date: "12/03/2026",
    views: 3568,
    downloads: 1641,
    description: "Đề mô phỏng chuẩn HSK 5 với mật độ từ vựng và bài đọc dài sát đề thi thật.",
    pdfUrl: samplePdfUrl,
    fileName: "de-thi-thu-hsk-5-so-5.pdf",
  },
  {
    id: 6,
    type: "exam",
    level: "HSK 6",
    brand: "Đề thi thử HSK 6",
    titleInner: "Đề mô phỏng HSK 6",
    subtitle: "Hiểu tổng hợp - Viết - Nghe",
    note: "Thời gian gợi ý: 140 phút",
    author: "Biên soạn: Tổ chuyên môn TOXI",
    name: "Đề thi thử HSK 6 số 6: luyện hiểu tổng hợp và nâng cao kỹ năng viết",
    date: "05/03/2026",
    views: 4412,
    downloads: 1984,
    description: "Tập trung vào các phần dễ mất điểm trong HSK 6, phù hợp cho giai đoạn nước rút trước thi.",
    pdfUrl: samplePdfUrl,
    fileName: "de-thi-thu-hsk-6-so-6.pdf",
  },
];

export const ALL_DOCUMENTS = [...DOC_DATA, ...EXAM_DATA];
